export const CREATE_BLOG = 'CREATE_BLOG';
export const FETCH_ALL_BLOG = 'FETCH_ALL_BLOG';
export const GET_BLOG_DETAIL = 'GET_BLOG_DETAIL';
export const FETCH_ALL_BOOKS = 'FETCH_ALL_BOOKS';
export const CREATE_BOOK = 'CREATE_BOOK';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const FETCH_ALL_PROJECT = 'FETCH_ALL_PROJECT';
